source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.contrib import admin
from django.urls import path, include


from webapp.views import IndexView, ArticleCreateView, ArticleView, ArticleUpdateView, ArticleDeleteView, \
    CommentCreateView, CommentIndexView, CommentUpdateView, CommentDeleteView, CommentForArticleCreateView



app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('article/create/', ArticleCreateView.as_view(), name='article_add'),
    path('article/<int:pk>', ArticleView.as_view(), name='article_view'),
    path('article/<int:pk>/edit/', ArticleUpdateView.as_view(), name='article_update'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
    path('comment/add/', CommentCreateView.as_view(), name='comment_add'),
    path('comment/', CommentIndexView.as_view(), name='comment_index'),
    path('comment/<int:pk>/edit/', CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('article/<int:pk>/add-comment/', CommentForArticleCreateView.as_view(), name='article_comment_create')

    ]

source/webapp/models.py
from django.db import models



class Article(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False, verbose_name='Заголовок')
    text = models.TextField(max_length=3000, null=False, blank=False, verbose_name='Текст')
    author = models.CharField(max_length=40, null=False, blank=False, default='Unknown', verbose_name='Автор')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    category = models.ForeignKey('webapp.Category', on_delete=models.PROTECT, null=True, blank=True,
                                 verbose_name='Категория ',  related_name='articles')
    tags = models.ManyToManyField('webapp.Tag', related_name='articles', through='webapp.ArticleTag',
                                  through_fields=('article', 'tag'), blank=True)

    def __str__(self):
        return "{}. {}".format(self.pk, self.title)




class Comment(models.Model):
    article = models.ForeignKey('webapp.Article', related_name='comments', on_delete=models.CASCADE,
                                verbose_name='Статья')
    text = models.TextField(max_length=400, verbose_name='Комментарий')
    author = models.CharField(max_length=40, null=True, blank=True, default='Аноним', verbose_name='Автор')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')

    def __str__(self):
        return self.text[:20]


class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name='Название')

    def __str__(self):
        return self.name



class Tag(models.Model):
    name = models.CharField(max_length=31, verbose_name='Тег')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')

    def __str__(self):
        return self.name


class ArticleTag(models.Model):
    article = models.ForeignKey('webapp.Article', related_name='article_tags', on_delete=models.CASCADE,
                                verbose_name='Статья')
    tag = models.ForeignKey('webapp.Tag', related_name='tag_articles', on_delete=models.CASCADE, verbose_name='Тег')

    def __str__(self):
        return "{} | {}".format(self.article, self.tag)

source/webapp/forms.py
from django import forms
from webapp.models import Article, Comment




class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        exclude = []




class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = []



class ArticleCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = []


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти")

source/webapp/views/article_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils.http import urlencode
from webapp.forms import ArticleForm, CommentForm, SimpleSearchForm
from webapp.models import Article
from django.views.generic import TemplateView, ListView, DeleteView, UpdateView, CreateView





class IndexView(ListView):
    context_object_name = 'articles'
    model = Article
    template_name = 'article/index.html'
    ordering = ['-created_at']
    paginate_by = 3
    paginate_orphans = 1


    def get(self, request, *args, **kwargs):
        form = SimpleSearchForm(self.request.GET)
        query = None
        if form.is_valid():
            query = form.cleaned_data['search']
        self.form = form
        self.query = query
        return super().get(request, *args, **kwargs)


    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        if self.query:
            context['query'] = urlencode({'search': self.query})
        context['form'] = self.form
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.query:
            queryset = queryset.filter(Q(title__icontains=self.query) | Q(author__icontains=self.query))
        return queryset





class ArticleView(TemplateView):
    template_name = 'article/article.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article_pk = kwargs.get('pk')
        article = get_object_or_404(Article, pk=article_pk)
        context['article'] = article
        context['form'] = CommentForm()
        comments = article.comments.order_by('-created_at')
        paginator = Paginator(comments, 3, 0)
        page_numder = self.request.GET.get('page', 1)
        page = paginator.get_page(page_numder)
        context['paginator'] = paginator
        context['page_obj'] = page
        context['comments'] = page.object_list
        context['is_paginated'] = page.has_other_pages()
        return context




class ArticleCreateView(LoginRequiredMixin, CreateView):
    template_name = 'article/create.html'
    form_class = ArticleForm
    model = Article

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return super().dispatch(request, *args, **kwargs)
        return redirect('accounts:login')

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.pk})







class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    template_name = 'article/update.html'
    form_class = ArticleForm
    context_object_name = 'article'

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.pk})




class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'article/delete.html'
    model = Article
    context_key = 'article'
    success_url = reverse_lazy('webapp:index')

source/webapp/views/base_views.py
from django.views.generic import TemplateView


class ListView(TemplateView):
    context_key = 'objects'
    model = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_objects()
        return context

    def get_objects(self):
        return self.model.objects.all()

source/webapp/views/comment_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View

from webapp.forms import CommentForm, ArticleCommentForm
from webapp.models import Comment, Article
from django.views.generic import ListView, DeleteView, UpdateView, CreateView


class CommentIndexView(ListView):
    template_name = 'comment/index.html'
    model = Comment
    context_object_name = 'comments'


class CommentForArticleCreateView(View):
    def post(self, request, *args, **kwargs):
        form = ArticleCommentForm(data=request.POST)
        article_pk = kwargs.get('pk')
        article = get_object_or_404(Article, pk=article_pk)
        if form.is_valid():
            Comment.objects.create(
                author=form.cleaned_data['author'],
                text=form.cleaned_data['text'],
                article=article

            )
            return redirect('webapp:article_view', pk=article_pk)
        else:
            return render(request, 'article/article.html', context={'form': form, 'article': article})





class CommentCreateView(LoginRequiredMixin, CreateView):
    template_name = 'article/create.html'
    form_class = CommentForm
    model = Comment

    def get_success_url(self):
        return reverse('webapp:comment_index', kwargs={'pk': self.object.pk})





class CommentUpdateView(LoginRequiredMixin, UpdateView):
    model = Comment
    template_name = 'comment/update.html'
    form_class = ArticleCommentForm
    context_object_name = 'comment'

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.article.pk})





class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.article.pk})

source/webapp/templates/article/article.html
{% extends 'base.html' %}

{% block title %}{{ article.title }}{% endblock %}

{% block menu %}
{% endblock %}

{% block content %}
    <h1 class="crearet">{{ article.title }}</h1>
     <p>Created by{{ article.author }}  ({{ article.category| default_if_none:'Без категорий' }})
            at {{ article.created_at|date:'d.n.Y H:i:s' }}</p>
    <div class="pre">{{ article.text }}</div>
    <hr>
    <h3>Comments:</h3>
{#    <p><a href="{% url 'article_comment_create' article.pk %}">Добавить комментарий</a></p>#}

    {% if is_paginated %}
         {% include 'partial/pagination.html' %}
    {% endif %}

    {% for comment in comments %}
        <div class="comment">
            <p>{{ comment.author }} commented at  {{ comment.created_at|date:'d.n.Y H:i:s' }} </p>
            <div class="pre">{{ comment.text }}</div>
        </div>
     {% empty %}
        <p>No comments yet.</p>
    {% endfor %}

  {% if is_paginated %}
         {% include 'partial/pagination.html' %}
    {% endif %}


    <h3>Добавить комментарий</h3>
        <form action="{% url 'webapp:article_comment_create' article.pk %}" method="post">
            {% include 'partial/form.html' with button_text='Add' %}
        </form>
{% endblock %}

source/webapp/templates/article/create.html
{% extends 'base.html' %}

    {% block title %}Create Article{% endblock %}

{% block content %}

<h1 class="crearet"> Create Article</h1>
<form method="POST" action="{% url "webapp:article_add" %}">
   {% include 'partial/form.html' with button_text='Create' %}
</form>
{% endblock %}

</body>
</html>

source/webapp/templates/article/delete.html
{% extends 'base.html' %}

    {% block title %}Delete Article{% endblock %}

{% block menu %}
    <li><a href="{% url 'webapp:article_view'  article.pk %}">View</a></li>
{% endblock %}

{% block content %}
    <form method="POST" action="{% url "webapp:article_delete" article.pk%}" class="text-center">
        <h1>Are you sure want to delete article "{{ article }}"?</h1>
        {% csrf_token %}
        <input type="submit" value="Confirm" class="btn btn-danger">
        <p><a href="{% url "webapp:article_view" article.pk %}" class="btn btn-primary">Cancel</a></p>
    </form>
{% endblock %}

</body>
</html>

source/webapp/templates/article/index.html
{% extends 'base.html' %}


{% block menu %}
    <li><a href="{% url 'webapp:article_add' %}">Add Article</a></li>
{% endblock %}

{% block content %}
<h1 style="text-align: center">Articles</h1>
    {% include 'partial/simple_search.html' %}

{% if is_paginated %}
   {% include 'partial/pagination.html' %}
{% endif %}

    {% for article in articles %}
        <h2>{{ article.title }}</h2>
        <p>Created by{{ article.author }}  ({{ article.category| default_if_none:'Без категорий' }})
            at {{ article.created_at|date:'d.n.Y H:i:s' }}</p>
        <p> <a href="{% url 'webapp:article_view' article.pk %}">More...</a>
            <a href="{% url 'webapp:article_update' article.pk %}">Edit</a>
            <a href="{% url 'webapp:article_delete' article.pk %}">Delete</a>

        </p>
        <hr>
    {% endfor %}

{% if is_paginated %}
   {% include 'partial/pagination.html' %}
{% endif %}

{% endblock %}

source/webapp/templates/article/update.html
{% extends 'base.html' %}

    {% block title %}Update Article{% endblock %}

{% block menu %}
    <li><a href="{% url 'webapp:article_view'  article.pk %}">View</a></li>
{% endblock %}

{% block content %}
<h1 class="crearet"> Update Article</h1>
<form method="POST" action="{% url "webapp:article_update" article.pk%}">
   {% include 'partial/form.html' with button_text='Update'%}
</form>
{% endblock %}